//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinicc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public int Id_doc { get; set; }
        public int Id_pat { get; set; }
        public int Id_schedule { get; set; }
        public System.DateTime time { get; set; }
        public Nullable<int> all_day { get; set; }
    }
}
